#!bin/bash
clear

echo @AccreditamentiUserBundle
./app/console --env=test behat --format=progress @AccreditamentiUserBundle

echo @AccreditamentiCongressiBundle
./app/console --env=test behat --format=progress @AccreditamentiCongressiBundle
