<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121022155148 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ideacpa_anagrafica ADD ente_citta VARCHAR(255) NOT NULL, ADD ente_provincia VARCHAR(255) NOT NULL, ADD ente_cap VARCHAR(255) NOT NULL, ADD ente_via VARCHAR(255) NOT NULL, ADD ente_numero_civico VARCHAR(255) NOT NULL, ADD ente_telefono VARCHAR(255) NOT NULL, ADD indirizzo_via VARCHAR(255) NOT NULL, DROP indirizzo, DROP citta, DROP provincia, DROP cap, DROP numero_civico, CHANGE sponsor iscritto_in_modo_autonomo TINYINT(1) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ideacpa_anagrafica ADD indirizzo VARCHAR(255) NOT NULL, ADD citta VARCHAR(255) NOT NULL, ADD provincia VARCHAR(255) NOT NULL, ADD cap VARCHAR(255) NOT NULL, ADD numero_civico VARCHAR(255) NOT NULL, DROP ente_citta, DROP ente_provincia, DROP ente_cap, DROP ente_via, DROP ente_numero_civico, DROP ente_telefono, DROP indirizzo_via, CHANGE iscritto_in_modo_autonomo sponsor TINYINT(1) NOT NULL");
    }
}
