<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121112150027 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Disciplina (id INT AUTO_INCREMENT NOT NULL, codice_professione INT DEFAULT NULL, codice INT NOT NULL, nome VARCHAR(255) NOT NULL, INDEX IDX_3D8E29F61B0BAAAD (codice_professione), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Professione (id INT AUTO_INCREMENT NOT NULL, codice INT NOT NULL, nome VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE Disciplina");
        $this->addSql("DROP TABLE Professione");
    }
}
