<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121022062108 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ideacpa_anagrafica ADD ente_appartenenza VARCHAR(255) NOT NULL, ADD citta VARCHAR(255) NOT NULL, ADD provincia VARCHAR(255) NOT NULL, ADD cap VARCHAR(255) NOT NULL, ADD numero_civico VARCHAR(255) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ideacpa_anagrafica DROP ente_appartenenza, DROP citta, DROP provincia, DROP cap, DROP numero_civico");
    }
}
