<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121114163617 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Disciplina DROP FOREIGN KEY FK_3D8E29F68B926C9E");
        $this->addSql("ALTER TABLE ideacpa_anagrafica DROP FOREIGN KEY FK_E5585A8384452F0F");
        $this->addSql("ALTER TABLE ideacpa_iscritti DROP FOREIGN KEY FK_5C45A58784452F0F");
        $this->addSql("ALTER TABLE ideacpa_questionario_customer_satisfaction DROP FOREIGN KEY FK_37CB54D984452F0F");
        $this->addSql("ALTER TABLE ideacpa_questionario_valutazione DROP FOREIGN KEY FK_6360642684452F0F");
        $this->addSql("ALTER TABLE ideacpa_questionarioecm DROP FOREIGN KEY FK_FC4C042984452F0F");
        $this->addSql("ALTER TABLE ideacpa_accreditamento DROP FOREIGN KEY FK_692C673AEE63296F");
        $this->addSql("ALTER TABLE ideacpa_risposta DROP FOREIGN KEY FK_E9D3DBEA9AA543D1");
        $this->addSql("ALTER TABLE ideacpa_domanda DROP FOREIGN KEY FK_33AAF6FB36292A9E");
        $this->addSql("ALTER TABLE ideacpa_domanda DROP FOREIGN KEY FK_33AAF6FBF0AF67DA");
        $this->addSql("ALTER TABLE ideacpa_domanda DROP FOREIGN KEY FK_33AAF6FB230E2EF9");
        $this->addSql("CREATE TABLE aim_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_C5B33BB192FC23A8 (username_canonical), UNIQUE INDEX UNIQ_C5B33BB1A0D96FBF (email_canonical), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_questionarioecm (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT NOT NULL, percentuale_risposte_esatte DOUBLE PRECISION NOT NULL, numero_tentativi_compilazione INT NOT NULL, data_inizio_compilazione DATE NOT NULL, data_fine_compilazione DATE NOT NULL, descrizione VARCHAR(255) NOT NULL, INDEX IDX_4514795E84452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_iscritti (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT NOT NULL, cognome VARCHAR(255) NOT NULL, nome VARCHAR(255) NOT NULL, codice_fiscale VARCHAR(255) NOT NULL, tipologia_iscritto VARCHAR(255) NOT NULL, INDEX IDX_1FF4EDA484452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_questionario_customer_satisfaction (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT NOT NULL, data_inizio_compilazione DATE NOT NULL, data_fine_compilazione DATE NOT NULL, descrizione VARCHAR(255) NOT NULL, INDEX IDX_E36130D984452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_congresso (id INT AUTO_INCREMENT NOT NULL, codice_congresso VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, titolo VARCHAR(255) NOT NULL, descrizione LONGTEXT DEFAULT NULL, data_inizio DATETIME NOT NULL, data_fine DATETIME NOT NULL, luogo VARCHAR(255) NOT NULL, manifesto VARCHAR(255) DEFAULT NULL, path_pdf_programma VARCHAR(255) DEFAULT NULL, path_pdf_iscrizione VARCHAR(255) DEFAULT NULL, path_pdf_prenotazione VARCHAR(255) DEFAULT NULL, email_referente VARCHAR(255) DEFAULT NULL, ricezione_abstract TINYINT(1) DEFAULT NULL, pagina_sponsor TINYINT(1) DEFAULT NULL, abilitato TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_risposte_utenti_questionario_ecm (id INT AUTO_INCREMENT NOT NULL, anagrafica_id INT NOT NULL, risposta_id INT NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_disciplina (id INT AUTO_INCREMENT NOT NULL, professione_id INT DEFAULT NULL, codice INT NOT NULL, nome VARCHAR(255) NOT NULL, INDEX IDX_85EDC17A8B926C9E (professione_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_questionario_valutazione (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT NOT NULL, data_inizio_compilazione DATE NOT NULL, data_fine_compilazione DATE NOT NULL, descrizione VARCHAR(255) NOT NULL, INDEX IDX_ED08AB1684452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_domanda (id INT AUTO_INCREMENT NOT NULL, questionarioecm_id INT DEFAULT NULL, questionario_cs_id INT DEFAULT NULL, questionario_valutazione_id INT DEFAULT NULL, descrizione VARCHAR(255) NOT NULL, INDEX IDX_EB0BBF93230E2EF9 (questionarioecm_id), INDEX IDX_EB0BBF9336292A9E (questionario_cs_id), INDEX IDX_EB0BBF93F0AF67DA (questionario_valutazione_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_accreditamento (id INT AUTO_INCREMENT NOT NULL, congresso_id INT DEFAULT NULL, numero_accreditamento DOUBLE PRECISION NOT NULL, titolo VARCHAR(255) NOT NULL, luogo VARCHAR(255) NOT NULL, data_inizio DATE NOT NULL, data_fine DATE NOT NULL, ore_formative VARCHAR(255) NOT NULL, obiettivo_formativo LONGTEXT NOT NULL, numero_crediti DOUBLE PRECISION NOT NULL, attiva_questionario TINYINT(1) DEFAULT NULL, supporto_aziende_sponsor LONGTEXT NOT NULL, certificato_ecm LONGTEXT DEFAULT NULL, INDEX IDX_5785194CEE63296F (congresso_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_anagrafica (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT DEFAULT NULL, tipo_iscrizione VARCHAR(255) NOT NULL, ente_appartenenza VARCHAR(255) NOT NULL, ente_citta VARCHAR(255) NOT NULL, ente_provincia VARCHAR(255) NOT NULL, ente_cap VARCHAR(255) NOT NULL, ente_via VARCHAR(255) NOT NULL, ente_numero_civico VARCHAR(255) NOT NULL, ente_telefono VARCHAR(255) NOT NULL, nome VARCHAR(255) NOT NULL, cognome VARCHAR(255) NOT NULL, data_nascita DATE NOT NULL, luogo_nascita VARCHAR(255) NOT NULL, codice_fiscale VARCHAR(255) NOT NULL, ordine_numero VARCHAR(255) NOT NULL, ordine_citta VARCHAR(255) NOT NULL, indirizzo_via VARCHAR(255) NOT NULL, indirizzo_numero_civico VARCHAR(255) NOT NULL, indirizzo_cap VARCHAR(255) NOT NULL, indirizzo_citta VARCHAR(255) NOT NULL, indirizzo_provincia VARCHAR(255) NOT NULL, telefono VARCHAR(255) NOT NULL, cellulare VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, professione VARCHAR(255) NOT NULL, disciplina VARCHAR(255) NOT NULL, qualifica VARCHAR(255) NOT NULL, iscritto_in_modo_autonomo TINYINT(1) NOT NULL, sponsor_azienda VARCHAR(255) NOT NULL, privacy TINYINT(1) NOT NULL, INDEX IDX_23F6A7F184452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_professione (id INT AUTO_INCREMENT NOT NULL, codice INT NOT NULL, nome VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_risposte_utenti_questionario_valutazione (id INT AUTO_INCREMENT NOT NULL, anagrafica_id INT NOT NULL, accreditamento_id INT NOT NULL, rilevanza_degli_argomenti VARCHAR(255) NOT NULL, qualita_educativa VARCHAR(255) NOT NULL, utilita_evento VARCHAR(255) NOT NULL, influenza_sponsor VARCHAR(255) NOT NULL, esempio_influenza_sponsor VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE aim_risposta (id INT AUTO_INCREMENT NOT NULL, domanda_id INT DEFAULT NULL, descrizione VARCHAR(255) NOT NULL, vero TINYINT(1) DEFAULT NULL, aperta TINYINT(1) NOT NULL, textarea TINYINT(1) NOT NULL, INDEX IDX_AA6293C99AA543D1 (domanda_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE aim_questionarioecm ADD CONSTRAINT FK_4514795E84452F0F FOREIGN KEY (accreditamento_id) REFERENCES aim_accreditamento(id)");
        $this->addSql("ALTER TABLE aim_iscritti ADD CONSTRAINT FK_1FF4EDA484452F0F FOREIGN KEY (accreditamento_id) REFERENCES aim_accreditamento(id)");
        $this->addSql("ALTER TABLE aim_questionario_customer_satisfaction ADD CONSTRAINT FK_E36130D984452F0F FOREIGN KEY (accreditamento_id) REFERENCES aim_accreditamento(id)");
        $this->addSql("ALTER TABLE aim_disciplina ADD CONSTRAINT FK_85EDC17A8B926C9E FOREIGN KEY (professione_id) REFERENCES aim_professione(id)");
        $this->addSql("ALTER TABLE aim_questionario_valutazione ADD CONSTRAINT FK_ED08AB1684452F0F FOREIGN KEY (accreditamento_id) REFERENCES aim_accreditamento(id)");
        $this->addSql("ALTER TABLE aim_domanda ADD CONSTRAINT FK_EB0BBF93230E2EF9 FOREIGN KEY (questionarioecm_id) REFERENCES aim_questionarioecm(id)");
        $this->addSql("ALTER TABLE aim_domanda ADD CONSTRAINT FK_EB0BBF9336292A9E FOREIGN KEY (questionario_cs_id) REFERENCES aim_questionario_customer_satisfaction(id)");
        $this->addSql("ALTER TABLE aim_domanda ADD CONSTRAINT FK_EB0BBF93F0AF67DA FOREIGN KEY (questionario_valutazione_id) REFERENCES aim_questionario_valutazione(id)");
        $this->addSql("ALTER TABLE aim_accreditamento ADD CONSTRAINT FK_5785194CEE63296F FOREIGN KEY (congresso_id) REFERENCES aim_congresso(id)");
        $this->addSql("ALTER TABLE aim_anagrafica ADD CONSTRAINT FK_23F6A7F184452F0F FOREIGN KEY (accreditamento_id) REFERENCES aim_accreditamento(id)");
        $this->addSql("ALTER TABLE aim_risposta ADD CONSTRAINT FK_AA6293C99AA543D1 FOREIGN KEY (domanda_id) REFERENCES aim_domanda(id)");
        $this->addSql("DROP TABLE Disciplina");
        $this->addSql("DROP TABLE Professione");
        $this->addSql("DROP TABLE RisposteUtentiQuestionarioValutazione");
        $this->addSql("DROP TABLE ideacpa_accreditamento");
        $this->addSql("DROP TABLE ideacpa_anagrafica");
        $this->addSql("DROP TABLE ideacpa_congresso");
        $this->addSql("DROP TABLE ideacpa_domanda");
        $this->addSql("DROP TABLE ideacpa_iscritti");
        $this->addSql("DROP TABLE ideacpa_questionario_customer_satisfaction");
        $this->addSql("DROP TABLE ideacpa_questionario_valutazione");
        $this->addSql("DROP TABLE ideacpa_questionarioecm");
        $this->addSql("DROP TABLE ideacpa_risposta");
        $this->addSql("DROP TABLE ideacpa_risposte_utenti_questionario_ecm");
        $this->addSql("DROP TABLE ideacpa_user");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE aim_domanda DROP FOREIGN KEY FK_EB0BBF93230E2EF9");
        $this->addSql("ALTER TABLE aim_domanda DROP FOREIGN KEY FK_EB0BBF9336292A9E");
        $this->addSql("ALTER TABLE aim_accreditamento DROP FOREIGN KEY FK_5785194CEE63296F");
        $this->addSql("ALTER TABLE aim_domanda DROP FOREIGN KEY FK_EB0BBF93F0AF67DA");
        $this->addSql("ALTER TABLE aim_risposta DROP FOREIGN KEY FK_AA6293C99AA543D1");
        $this->addSql("ALTER TABLE aim_questionarioecm DROP FOREIGN KEY FK_4514795E84452F0F");
        $this->addSql("ALTER TABLE aim_iscritti DROP FOREIGN KEY FK_1FF4EDA484452F0F");
        $this->addSql("ALTER TABLE aim_questionario_customer_satisfaction DROP FOREIGN KEY FK_E36130D984452F0F");
        $this->addSql("ALTER TABLE aim_questionario_valutazione DROP FOREIGN KEY FK_ED08AB1684452F0F");
        $this->addSql("ALTER TABLE aim_anagrafica DROP FOREIGN KEY FK_23F6A7F184452F0F");
        $this->addSql("ALTER TABLE aim_disciplina DROP FOREIGN KEY FK_85EDC17A8B926C9E");
        $this->addSql("CREATE TABLE Disciplina (id INT AUTO_INCREMENT NOT NULL, professione_id INT DEFAULT NULL, codice INT NOT NULL, nome VARCHAR(255) NOT NULL, INDEX IDX_3D8E29F68B926C9E (professione_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Professione (id INT AUTO_INCREMENT NOT NULL, codice INT NOT NULL, nome VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE RisposteUtentiQuestionarioValutazione (id INT AUTO_INCREMENT NOT NULL, anagrafica_id INT NOT NULL, accreditamento_id INT NOT NULL, rilevanza_degli_argomenti VARCHAR(255) NOT NULL, qualita_educativa VARCHAR(255) NOT NULL, utilita_evento VARCHAR(255) NOT NULL, influenza_sponsor VARCHAR(255) NOT NULL, esempio_influenza_sponsor VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ideacpa_accreditamento (id INT AUTO_INCREMENT NOT NULL, congresso_id INT DEFAULT NULL, numero_accreditamento DOUBLE PRECISION NOT NULL, titolo VARCHAR(255) NOT NULL, luogo VARCHAR(255) NOT NULL, data_inizio DATE NOT NULL, data_fine DATE NOT NULL, ore_formative VARCHAR(255) NOT NULL, obiettivo_formativo LONGTEXT NOT NULL, numero_crediti DOUBLE PRECISION NOT NULL, attiva_questionario TINYINT(1) DEFAULT NULL, supporto_aziende_sponsor LONGTEXT NOT NULL, certificato_ecm LONGTEXT DEFAULT NULL, INDEX IDX_692C673AEE63296F (congresso_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ideacpa_anagrafica (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT DEFAULT NULL, tipo_iscrizione VARCHAR(255) NOT NULL, nome VARCHAR(255) NOT NULL, cognome VARCHAR(255) NOT NULL, data_nascita DATE NOT NULL, luogo_nascita VARCHAR(255) NOT NULL, codice_fiscale VARCHAR(255) NOT NULL, ordine_numero VARCHAR(255) NOT NULL, ordine_citta VARCHAR(255) NOT NULL, indirizzo_cap VARCHAR(255) NOT NULL, indirizzo_citta VARCHAR(255) NOT NULL, indirizzo_provincia VARCHAR(255) NOT NULL, telefono VARCHAR(255) NOT NULL, cellulare VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, professione VARCHAR(255) NOT NULL, disciplina VARCHAR(255) NOT NULL, qualifica VARCHAR(255) NOT NULL, iscritto_in_modo_autonomo TINYINT(1) NOT NULL, sponsor_azienda VARCHAR(255) NOT NULL, privacy TINYINT(1) NOT NULL, ente_appartenenza VARCHAR(255) NOT NULL, ente_citta VARCHAR(255) NOT NULL, ente_provincia VARCHAR(255) NOT NULL, ente_cap VARCHAR(255) NOT NULL, ente_via VARCHAR(255) NOT NULL, ente_numero_civico VARCHAR(255) NOT NULL, ente_telefono VARCHAR(255) NOT NULL, indirizzo_via VARCHAR(255) NOT NULL, indirizzo_numero_civico VARCHAR(255) NOT NULL, INDEX IDX_E5585A8384452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ideacpa_congresso (id INT AUTO_INCREMENT NOT NULL, codice_congresso VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, titolo VARCHAR(255) NOT NULL, descrizione LONGTEXT DEFAULT NULL, data_inizio DATETIME NOT NULL, data_fine DATETIME NOT NULL, luogo VARCHAR(255) NOT NULL, manifesto VARCHAR(255) DEFAULT NULL, path_pdf_programma VARCHAR(255) DEFAULT NULL, path_pdf_iscrizione VARCHAR(255) DEFAULT NULL, path_pdf_prenotazione VARCHAR(255) DEFAULT NULL, email_referente VARCHAR(255) DEFAULT NULL, ricezione_abstract TINYINT(1) DEFAULT NULL, pagina_sponsor TINYINT(1) DEFAULT NULL, abilitato TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ideacpa_domanda (id INT AUTO_INCREMENT NOT NULL, questionarioecm_id INT DEFAULT NULL, questionario_cs_id INT DEFAULT NULL, questionario_valutazione_id INT DEFAULT NULL, descrizione VARCHAR(255) NOT NULL, INDEX IDX_33AAF6FB230E2EF9 (questionarioecm_id), INDEX IDX_33AAF6FB36292A9E (questionario_cs_id), INDEX IDX_33AAF6FBF0AF67DA (questionario_valutazione_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ideacpa_iscritti (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT NOT NULL, cognome VARCHAR(255) NOT NULL, nome VARCHAR(255) NOT NULL, codice_fiscale VARCHAR(255) NOT NULL, tipologia_iscritto VARCHAR(255) NOT NULL, INDEX IDX_5C45A58784452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ideacpa_questionario_customer_satisfaction (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT NOT NULL, data_inizio_compilazione DATE NOT NULL, data_fine_compilazione DATE NOT NULL, descrizione VARCHAR(255) NOT NULL, INDEX IDX_37CB54D984452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ideacpa_questionario_valutazione (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT NOT NULL, data_inizio_compilazione DATE NOT NULL, data_fine_compilazione DATE NOT NULL, descrizione VARCHAR(255) NOT NULL, INDEX IDX_6360642684452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ideacpa_questionarioecm (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT NOT NULL, descrizione VARCHAR(255) NOT NULL, data_inizio_compilazione DATE NOT NULL, data_fine_compilazione DATE NOT NULL, percentuale_risposte_esatte DOUBLE PRECISION NOT NULL, numero_tentativi_compilazione INT NOT NULL, INDEX IDX_FC4C042984452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ideacpa_risposta (id INT AUTO_INCREMENT NOT NULL, domanda_id INT DEFAULT NULL, descrizione VARCHAR(255) NOT NULL, vero TINYINT(1) DEFAULT NULL, aperta TINYINT(1) NOT NULL, textarea TINYINT(1) NOT NULL, INDEX IDX_E9D3DBEA9AA543D1 (domanda_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ideacpa_risposte_utenti_questionario_ecm (id INT AUTO_INCREMENT NOT NULL, anagrafica_id INT NOT NULL, risposta_id INT NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ideacpa_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_35C5D55C92FC23A8 (username_canonical), UNIQUE INDEX UNIQ_35C5D55CA0D96FBF (email_canonical), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Disciplina ADD CONSTRAINT FK_3D8E29F68B926C9E FOREIGN KEY (professione_id) REFERENCES Professione(id)");
        $this->addSql("ALTER TABLE ideacpa_accreditamento ADD CONSTRAINT FK_692C673AEE63296F FOREIGN KEY (congresso_id) REFERENCES ideacpa_congresso(id)");
        $this->addSql("ALTER TABLE ideacpa_anagrafica ADD CONSTRAINT FK_E5585A8384452F0F FOREIGN KEY (accreditamento_id) REFERENCES ideacpa_accreditamento(id)");
        $this->addSql("ALTER TABLE ideacpa_domanda ADD CONSTRAINT FK_33AAF6FB230E2EF9 FOREIGN KEY (questionarioecm_id) REFERENCES ideacpa_questionarioecm(id)");
        $this->addSql("ALTER TABLE ideacpa_domanda ADD CONSTRAINT FK_33AAF6FB36292A9E FOREIGN KEY (questionario_cs_id) REFERENCES ideacpa_questionario_customer_satisfaction(id)");
        $this->addSql("ALTER TABLE ideacpa_domanda ADD CONSTRAINT FK_33AAF6FBF0AF67DA FOREIGN KEY (questionario_valutazione_id) REFERENCES ideacpa_questionario_valutazione(id)");
        $this->addSql("ALTER TABLE ideacpa_iscritti ADD CONSTRAINT FK_5C45A58784452F0F FOREIGN KEY (accreditamento_id) REFERENCES ideacpa_accreditamento(id)");
        $this->addSql("ALTER TABLE ideacpa_questionario_customer_satisfaction ADD CONSTRAINT FK_37CB54D984452F0F FOREIGN KEY (accreditamento_id) REFERENCES ideacpa_accreditamento(id)");
        $this->addSql("ALTER TABLE ideacpa_questionario_valutazione ADD CONSTRAINT FK_6360642684452F0F FOREIGN KEY (accreditamento_id) REFERENCES ideacpa_accreditamento(id)");
        $this->addSql("ALTER TABLE ideacpa_questionarioecm ADD CONSTRAINT FK_FC4C042984452F0F FOREIGN KEY (accreditamento_id) REFERENCES ideacpa_accreditamento(id)");
        $this->addSql("ALTER TABLE ideacpa_risposta ADD CONSTRAINT FK_E9D3DBEA9AA543D1 FOREIGN KEY (domanda_id) REFERENCES ideacpa_domanda(id)");
        $this->addSql("DROP TABLE aim_user");
        $this->addSql("DROP TABLE aim_questionarioecm");
        $this->addSql("DROP TABLE aim_iscritti");
        $this->addSql("DROP TABLE aim_questionario_customer_satisfaction");
        $this->addSql("DROP TABLE aim_congresso");
        $this->addSql("DROP TABLE aim_risposte_utenti_questionario_ecm");
        $this->addSql("DROP TABLE aim_disciplina");
        $this->addSql("DROP TABLE aim_questionario_valutazione");
        $this->addSql("DROP TABLE aim_domanda");
        $this->addSql("DROP TABLE aim_accreditamento");
        $this->addSql("DROP TABLE aim_anagrafica");
        $this->addSql("DROP TABLE aim_professione");
        $this->addSql("DROP TABLE aim_risposte_utenti_questionario_valutazione");
        $this->addSql("DROP TABLE aim_risposta");
    }
}
