<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120627173340 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ideacpa_questionario_customer_satisfaction (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT NOT NULL, data_inizio_compilazione DATE NOT NULL, data_fine_compilazione DATE NOT NULL, descrizione VARCHAR(255) NOT NULL, INDEX IDX_37CB54D984452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE ideacpa_questionario_customer_satisfaction ADD CONSTRAINT FK_37CB54D984452F0F FOREIGN KEY (accreditamento_id) REFERENCES ideacpa_accreditamento(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE ideacpa_questionario_customer_satisfaction");
    }
}
