<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120625151406 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ideacpa_congresso CHANGE codice_congresso codice_congresso VARCHAR(255) DEFAULT NULL, CHANGE url url VARCHAR(255) DEFAULT NULL, CHANGE descrizione descrizione LONGTEXT DEFAULT NULL, CHANGE ricezione_abstract ricezione_abstract TINYINT(1) DEFAULT NULL, CHANGE pagina_sponsor pagina_sponsor TINYINT(1) DEFAULT NULL, CHANGE abilitato abilitato TINYINT(1) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ideacpa_congresso CHANGE codice_congresso codice_congresso VARCHAR(255) NOT NULL, CHANGE url url VARCHAR(255) NOT NULL, CHANGE descrizione descrizione LONGTEXT NOT NULL, CHANGE ricezione_abstract ricezione_abstract TINYINT(1) NOT NULL, CHANGE pagina_sponsor pagina_sponsor TINYINT(1) NOT NULL, CHANGE abilitato abilitato TINYINT(1) NOT NULL");
    }
}
