<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121116022621 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE aim_anagrafica ADD dichiara_sponsor_azienda VARCHAR(255) NOT NULL, ADD dichiara_autorizzazione_struttura VARCHAR(255) NOT NULL, ADD dichiara_informato_dal_provider VARCHAR(255) NOT NULL, CHANGE iscritto_in_modo_autonomo iscritto_in_modo_autonomo VARCHAR(255) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE aim_anagrafica DROP dichiara_sponsor_azienda, DROP dichiara_autorizzazione_struttura, DROP dichiara_informato_dal_provider, CHANGE iscritto_in_modo_autonomo iscritto_in_modo_autonomo TINYINT(1) NOT NULL");
    }
}
