<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120619220654 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE QuestionarioEcm ADD CONSTRAINT FK_7C095A3384452F0F FOREIGN KEY (accreditamento_id) REFERENCES ideacpa_accreditamento(id)");
        $this->addSql("CREATE INDEX IDX_7C095A3384452F0F ON QuestionarioEcm (accreditamento_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE QuestionarioEcm DROP FOREIGN KEY FK_7C095A3384452F0F");
        $this->addSql("DROP INDEX IDX_7C095A3384452F0F ON QuestionarioEcm");
    }
}
