<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120801162140 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE ideacpa_questionario_valutazione");
        $this->addSql("ALTER TABLE ideacpa_domanda ADD questionario_cs_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE ideacpa_domanda ADD CONSTRAINT FK_33AAF6FB36292A9E FOREIGN KEY (questionario_cs_id) REFERENCES ideacpa_questionario_customer_satisfaction(id)");
        $this->addSql("CREATE INDEX IDX_33AAF6FB36292A9E ON ideacpa_domanda (questionario_cs_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ideacpa_questionario_valutazione (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT NOT NULL, data_inizio_compilazione DATE NOT NULL, data_fine_compilazione DATE NOT NULL, descrizione VARCHAR(255) NOT NULL, INDEX IDX_6360642684452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE ideacpa_questionario_valutazione ADD CONSTRAINT FK_6360642684452F0F FOREIGN KEY (accreditamento_id) REFERENCES ideacpa_accreditamento(id)");
        $this->addSql("ALTER TABLE ideacpa_domanda DROP FOREIGN KEY FK_33AAF6FB36292A9E");
        $this->addSql("DROP INDEX IDX_33AAF6FB36292A9E ON ideacpa_domanda");
        $this->addSql("ALTER TABLE ideacpa_domanda DROP questionario_cs_id");
    }
}
