<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120608203015 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ideacpa_congresso CHANGE path_pdf_programma path_pdf_programma VARCHAR(255) DEFAULT NULL, CHANGE path_pdf_iscrizione path_pdf_iscrizione VARCHAR(255) DEFAULT NULL, CHANGE path_pdf_prenotazione path_pdf_prenotazione VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ideacpa_congresso CHANGE path_pdf_programma path_pdf_programma VARCHAR(255) NOT NULL, CHANGE path_pdf_iscrizione path_pdf_iscrizione VARCHAR(255) NOT NULL, CHANGE path_pdf_prenotazione path_pdf_prenotazione VARCHAR(255) NOT NULL");
    }
}
