<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120801172720 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ideacpa_questionario_valutazione (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT NOT NULL, data_inizio_compilazione DATE NOT NULL, data_fine_compilazione DATE NOT NULL, descrizione VARCHAR(255) NOT NULL, INDEX IDX_6360642684452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE ideacpa_questionario_valutazione ADD CONSTRAINT FK_6360642684452F0F FOREIGN KEY (accreditamento_id) REFERENCES ideacpa_accreditamento(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE ideacpa_questionario_valutazione");
    }
}
