<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120622103532 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ideacpa_domanda (id INT AUTO_INCREMENT NOT NULL, questionarioecm_id INT DEFAULT NULL, descrizione VARCHAR(255) NOT NULL, INDEX IDX_33AAF6FB230E2EF9 (questionarioecm_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE ideacpa_domanda ADD CONSTRAINT FK_33AAF6FB230E2EF9 FOREIGN KEY (questionarioecm_id) REFERENCES ideacpa_questionarioecm(id)");
        $this->addSql("DROP TABLE Domanda");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Domanda (id INT AUTO_INCREMENT NOT NULL, questionarioecm_id INT DEFAULT NULL, descrizione VARCHAR(255) NOT NULL, INDEX IDX_4FDF0946230E2EF9 (questionarioecm_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Domanda ADD CONSTRAINT FK_4FDF0946230E2EF9 FOREIGN KEY (questionarioecm_id) REFERENCES ideacpa_questionarioecm(id)");
        $this->addSql("DROP TABLE ideacpa_domanda");
    }
}
