<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121116160931 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE aim_anagrafica CHANGE dichiara_sponsor_azienda dichiara_sponsor_azienda VARCHAR(255) DEFAULT NULL, CHANGE dichiara_autorizzazione_struttura dichiara_autorizzazione_struttura VARCHAR(255) DEFAULT NULL, CHANGE dichiara_informato_dal_provider dichiara_informato_dal_provider VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE aim_anagrafica CHANGE dichiara_sponsor_azienda dichiara_sponsor_azienda VARCHAR(255) NOT NULL, CHANGE dichiara_autorizzazione_struttura dichiara_autorizzazione_struttura VARCHAR(255) NOT NULL, CHANGE dichiara_informato_dal_provider dichiara_informato_dal_provider VARCHAR(255) NOT NULL");
    }
}
