<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121116151152 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE aim_anagrafica CHANGE ente_appartenenza ente_appartenenza VARCHAR(255) DEFAULT NULL, CHANGE ente_citta ente_citta VARCHAR(255) DEFAULT NULL, CHANGE ente_provincia ente_provincia VARCHAR(255) DEFAULT NULL, CHANGE ente_cap ente_cap VARCHAR(255) DEFAULT NULL, CHANGE ente_via ente_via VARCHAR(255) DEFAULT NULL, CHANGE ente_numero_civico ente_numero_civico VARCHAR(255) DEFAULT NULL, CHANGE ente_telefono ente_telefono VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE aim_anagrafica CHANGE ente_appartenenza ente_appartenenza VARCHAR(255) NOT NULL, CHANGE ente_citta ente_citta VARCHAR(255) NOT NULL, CHANGE ente_provincia ente_provincia VARCHAR(255) NOT NULL, CHANGE ente_cap ente_cap VARCHAR(255) NOT NULL, CHANGE ente_via ente_via VARCHAR(255) NOT NULL, CHANGE ente_numero_civico ente_numero_civico VARCHAR(255) NOT NULL, CHANGE ente_telefono ente_telefono VARCHAR(255) NOT NULL");
    }
}
