<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120608221428 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ideacpa_accreditamento ADD congresso_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE ideacpa_accreditamento ADD CONSTRAINT FK_692C673AEE63296F FOREIGN KEY (congresso_id) REFERENCES ideacpa_congresso(id)");
        $this->addSql("CREATE INDEX IDX_692C673AEE63296F ON ideacpa_accreditamento (congresso_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ideacpa_accreditamento DROP FOREIGN KEY FK_692C673AEE63296F");
        $this->addSql("DROP INDEX IDX_692C673AEE63296F ON ideacpa_accreditamento");
        $this->addSql("ALTER TABLE ideacpa_accreditamento DROP congresso_id");
    }
}
