<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120801174051 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ideacpa_domanda ADD questionario_valutazione_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE ideacpa_domanda ADD CONSTRAINT FK_33AAF6FBF0AF67DA FOREIGN KEY (questionario_valutazione_id) REFERENCES ideacpa_questionario_valutazione(id)");
        $this->addSql("CREATE INDEX IDX_33AAF6FBF0AF67DA ON ideacpa_domanda (questionario_valutazione_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ideacpa_domanda DROP FOREIGN KEY FK_33AAF6FBF0AF67DA");
        $this->addSql("DROP INDEX IDX_33AAF6FBF0AF67DA ON ideacpa_domanda");
        $this->addSql("ALTER TABLE ideacpa_domanda DROP questionario_valutazione_id");
    }
}
