<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120621124434 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ideacpa_questionarioecm (id INT AUTO_INCREMENT NOT NULL, accreditamento_id INT NOT NULL, descrizione VARCHAR(255) NOT NULL, data_inizio_compilazione DATE NOT NULL, data_fine_compilazione DATE NOT NULL, percentuale_risposte_esatte DOUBLE PRECISION NOT NULL, numero_tentativi_compilazione INT NOT NULL, INDEX IDX_FC4C042984452F0F (accreditamento_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE ideacpa_questionarioecm ADD CONSTRAINT FK_FC4C042984452F0F FOREIGN KEY (accreditamento_id) REFERENCES ideacpa_accreditamento(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE ideacpa_questionarioecm");
    }
}
