<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121116160432 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE aim_anagrafica DROP iscritto_in_modo_autonomo, DROP sponsor_azienda, CHANGE cellulare cellulare VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE aim_anagrafica ADD iscritto_in_modo_autonomo VARCHAR(255) NOT NULL, ADD sponsor_azienda VARCHAR(255) NOT NULL, CHANGE cellulare cellulare VARCHAR(255) NOT NULL");
    }
}
