<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120907112155 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Anagrafica ADD accreditamento_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Anagrafica ADD CONSTRAINT FK_9B954F7D84452F0F FOREIGN KEY (accreditamento_id) REFERENCES ideacpa_accreditamento(id)");
        $this->addSql("CREATE INDEX IDX_9B954F7D84452F0F ON Anagrafica (accreditamento_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Anagrafica DROP FOREIGN KEY FK_9B954F7D84452F0F");
        $this->addSql("DROP INDEX IDX_9B954F7D84452F0F ON Anagrafica");
        $this->addSql("ALTER TABLE Anagrafica DROP accreditamento_id");
    }
}
