<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120608213947 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ideacpa_accreditamento (id INT AUTO_INCREMENT NOT NULL, numero_accreditamento DOUBLE PRECISION NOT NULL, titolo VARCHAR(255) NOT NULL, luogo VARCHAR(255) NOT NULL, data_inizio DATE NOT NULL, data_fine DATE NOT NULL, ore_formative VARCHAR(255) NOT NULL, obiettivo_formativo LONGTEXT NOT NULL, numero_crediti DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE Accreditamento");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Accreditamento (id INT AUTO_INCREMENT NOT NULL, numero_accreditamento DOUBLE PRECISION NOT NULL, titolo VARCHAR(255) NOT NULL, luogo VARCHAR(255) NOT NULL, data_inizio DATE NOT NULL, data_fine DATE NOT NULL, ore_formative VARCHAR(255) NOT NULL, obiettivo_formativo LONGTEXT NOT NULL, numero_crediti DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE ideacpa_accreditamento");
    }
}
