<?php

namespace Accreditamenti\CongressiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Accreditamenti\CongressiBundle\Entity\Congresso;

/**
 * AccreditamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccreditamentoRepository extends EntityRepository
{
    public function findAllByCongresso(Congresso $congresso)
    {
        return $this->createQueryBuilder('a')
                        ->where('a.congresso = ' . $congresso->getId())
                        ->getQuery()
                        ->getResult();
    }
    

}
