<?php

namespace Accreditamenti\CongressiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CongressoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CongressoRepository extends EntityRepository {

    public function getCongressiFuturiAbilitati() {
        return $this->createQueryBuilder('c')
                        ->where('c.abilitato = :abilitato')
                        ->andWhere('c.data_inizio >= :data_inizio')
                        ->setParameter('abilitato', true)
                        ->setParameter('data_inizio', new \DateTime())
                        ->orderBy('c.data_inizio', 'asc')
                        ->getQuery()
                        ->getResult();
    }

    public function getCongressiFuturiTutti() {
        return $this->createQueryBuilder('c')
                        ->andWhere('c.data_inizio >= :data_inizio')
                        ->setParameter('data_inizio', new \DateTime())
                        ->orderBy('c.data_inizio', 'asc')
                        ->getQuery()
                        ->getResult();
    }

}