<?php

namespace Accreditamenti\CongressiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Accreditamenti\CongressiBundle\Entity\QuestionarioEcm;

/**
 * DomandaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomandaRepository extends EntityRepository {

    public function findDomandeDelQuestionario(QuestionarioEcm $questionario) {
        return $this->createQueryBuilder('d')
                        ->join('d.questionarioecm', 'questionario')
                        ->where('d.questionarioecm = :questionario')
                        ->setParameter('questionario', $questionario)
                        ->getQuery()
                        ->getResult();
    }

    
}