<?php

namespace Accreditamenti\CongressiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfessioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessioneRepository extends EntityRepository
{
}