Feature: Registrazione ad un accreditamento login e compilo anagrafica

Scenario: Voglio scegliere un congresso da un elenco e un relativo suo accreditamento
    Given I go to "/"
    And I follow "Login"
    When I fill in "_username" with "giuseppe"
    And I fill in "_password" with "giuseppe"
    Given I press "Login"
    When I am on "/congresso/new"
    #Then show last response
    And I fill in "Codice congresso" with "SIP2012"
    And I fill in "Url" with "http://www.google.com"
    And I fill in "Titolo" with "68° Congresso Nazionale SIP"
    And I fill in "Descrizione" with "mia descrizione"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_day" with "01"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_month" with "11"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_year" with "2012"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_day" with "11"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_month" with "11"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_year" with "2012"
    And I fill in "Luogo" with "Roma"
    And I fill in "accreditamenti_congressibundle_congressotype_manifesto" with "/manifeso.jpg"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_programma" with "/home/programma.pdf"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_iscrizione" with "/home/iscrizione.pdf"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_prenotazione" with "/home/prenotazione.pdf"
    And I fill in "Email referente" with "giuseppe.rubino@gmail.com"
    And I check "Ricezione abstract"
    And I check "Pagina sponsor"
    And I check "Abilitato"
    Given I press "Create"
    When I follow "link_accreditamento_new"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_numero_accreditamento" with "33"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_titolo" with "TitoloAccreditamento"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_luogo" with "Cesena"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_data_inizio_day" with "01"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_data_inizio_month" with "11"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_data_inizio_year" with "2012"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_data_fine_day" with "11"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_data_fine_month" with "11"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_data_fine_year" with "2012"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_ore_formative" with "2012"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_obiettivo_formativo" with "Descrizione dell'obiettivo ..."
    And I fill in "accreditamenti_congressibundle_accreditamentotype_numero_crediti" with "2012"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_supporto_aziende_sponsor" with "Mellin, plasmon, chicco"

    Given I press "Create"
    
    When I follow "Quest. ecm"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_descrizione" with "Esempio Questionario ECM"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_data_inizio_compilazione_day" with "01"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_data_inizio_compilazione_month" with "11"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_data_inizio_compilazione_year" with "2012"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_data_fine_compilazione_day" with "11"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_data_fine_compilazione_month" with "11"   
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_data_fine_compilazione_year" with "2012"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_percentuale_risposte_esatte" with "70"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_numero_tentativi_compilazione" with "10"
    Given I press "Create"

    #Creo anche una domana e tre risposte
    When I follow "Crea domanda"
    And I fill in "accreditamenti_congressibundle_domandatype_descrizione" with "Chi ha rubato la marmellata?"
    Given I press "Create"
    When I follow "aggiungi risposta"
    And I fill in "accreditamenti_congressibundle_rispostatype_descrizione" with "Pippo Baudo"
    Given I press "Create"
    When I follow "aggiungi risposta"
    And I fill in "accreditamenti_congressibundle_rispostatype_descrizione" with "Silvio Barlusconi"
    Given I press "Create"
    When I follow "aggiungi risposta"
    And I fill in "accreditamenti_congressibundle_rispostatype_descrizione" with "Gianluca"
    And I check "Vero"
    Given I press "Create"

    # Seconda domanda e risposte
    When I follow "Crea domanda"
    And I fill in "accreditamenti_congressibundle_domandatype_descrizione" with "Chi il piu brutto del reame?"
    Given I press "Create"
    When I follow "aggiungi risposta"
    And I fill in "accreditamenti_congressibundle_rispostatype_descrizione" with "io"
    Given I press "Create"
    When I follow "aggiungi risposta"
    And I fill in "accreditamenti_congressibundle_rispostatype_descrizione" with "tu"
    Given I press "Create"
    When I follow "aggiungi risposta"
    And I fill in "accreditamenti_congressibundle_rispostatype_descrizione" with "lui"
    And I check "Vero"
    Given I press "Create"

    And last accreditamento has "Giuseppe" "Rubino" "RBNGPP74B15E882U" "PAR" as attendee
    Given I go to "/congresso/ultimo"
    When I follow "link_accesso_accreditamento"
    And I fill in "form[codice_fiscale]" with "RBNGPP74B15"
    Given I press "Accedi"

    Then the response should contain "Codice_fiscale non presente per questo accreditamento"
    And I fill in "form[codice_fiscale]" with "RBNGPP74B15E882U"
    Given I press "Accedi"




    Then the response should contain "Benvenuto Rubino Giuseppe Login effettuato con successo"
    And I fill in "accreditamenti_congressibundle_anagraficatype_tipo_iscrizione" with "P"
    And I fill in "accreditamenti_congressibundle_anagraficatype_nome" with "Giuseppe"
    And I fill in "accreditamenti_congressibundle_anagraficatype_cognome" with "Rubino"
    And I fill in "accreditamenti_congressibundle_anagraficatype_luogo_nascita" with "Manduria (TA)"
    And I fill in "accreditamenti_congressibundle_anagraficatype_data_nascita" with "15-02-1974"
    And I fill in "accreditamenti_congressibundle_anagraficatype_codice_fiscale" with "RBNGPP74B15E882U"
    And I fill in "accreditamenti_congressibundle_anagraficatype_indirizzo_via" with "Piazzale delle province"
    And I fill in "accreditamenti_congressibundle_anagraficatype_indirizzo_numero_civico" with "9"
    And I fill in "accreditamenti_congressibundle_anagraficatype_indirizzo_cap" with "00159"
    And I fill in "accreditamenti_congressibundle_anagraficatype_indirizzo_citta" with "Roma"
    And I fill in "accreditamenti_congressibundle_anagraficatype_indirizzo_provincia" with "RM"
    And I fill in "accreditamenti_congressibundle_anagraficatype_telefono" with "0644234"
    And I fill in "accreditamenti_congressibundle_anagraficatype_cellulare" with "RM"
    And I fill in "accreditamenti_congressibundle_anagraficatype_email" with "giuseppe.rubino@gmail.com"
    And I fill in "accreditamenti_congressibundle_anagraficatype_professione" with "1"
    And I fill in "accreditamenti_congressibundle_anagraficatype_disciplina" with "24"
    And I fill in "accreditamenti_congressibundle_anagraficatype_ordine_numero" with "12312"
    And I fill in "accreditamenti_congressibundle_anagraficatype_ordine_citta" with "Roma"
    And I fill in "accreditamenti_congressibundle_anagraficatype_qualifica" with "L"
    #Then show last response
    And I fill in "accreditamenti_congressibundle_anagraficatype_ente_appartenenza" with "nome ente di appartenenza test"
    And I fill in "accreditamenti_congressibundle_anagraficatype_ente_citta" with "citta ente di appartenenza test"
    And I fill in "accreditamenti_congressibundle_anagraficatype_ente_provincia" with "provincia ente di appartenenza test"
    And I fill in "accreditamenti_congressibundle_anagraficatype_ente_cap" with "cap ente di appartenenza test"
    And I fill in "accreditamenti_congressibundle_anagraficatype_ente_via" with "via ente di appartenenza test" 
    And I fill in "accreditamenti_congressibundle_anagraficatype_ente_numero_civico" with "numero civico ente di appartenenza test"     
    And I fill in "accreditamenti_congressibundle_anagraficatype_ente_telefono" with "telefono ente di appartenenza test"     

    And I check "accreditamenti_congressibundle_anagraficatype_informazioni_veritiere"
    And I fill in "accreditamenti_congressibundle_anagraficatype_dichiara_sponsor_azienda" with "Nestlè"
    And I fill in "accreditamenti_congressibundle_anagraficatype_dichiara_autorizzazione_struttura" with "Si"
    And I fill in "accreditamenti_congressibundle_anagraficatype_dichiara_informato_dal_provider" with "Si"
    And I check "accreditamenti_congressibundle_anagraficatype_privacy"
    Then show last response
    Given I press "Avanti"
    #Then show last response
    Then the response should contain "Compila il questionario ECM"