Feature: Come Admin voglio gestire i congressi

Scenario: As Guest I want to login
    Given I go to "/"
    Then the response should not contain "crea congresso"
    Then the response should not contain "link-crea-nuovo-congresso"
    And I follow "Login"
    When I fill in "_username" with "giuseppe"
    And I fill in "_password" with "giuseppe"
    Given I press "Login"
    Then the response should contain "logout (giuseppe)"
    Given I go to "/"

Scenario: As User Create a new Congress
    Given I go to "/"
    And I follow "Login"
    When I fill in "_username" with "giuseppe"
    And I fill in "_password" with "giuseppe"
    Given I press "Login"
    When I am on "/congresso/new"
    And I fill in "Codice congresso" with "TEST89"
    And I fill in "Url" with "http://www.google.com"
    And I fill in "Titolo" with "titolo test"
    And I fill in "Descrizione" with "mia descrizione"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_year" with "2012"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_month" with "09"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_day" with "01"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_year" with "2012"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_month" with "09"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_day" with "01"
    And I fill in "Luogo" with "Roma"
    And I fill in "accreditamenti_congressibundle_congressotype_manifesto" with "/manifeso.jpg"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_programma" with "/home/programma.pdf"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_iscrizione" with "/home/iscrizione.pdf"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_prenotazione" with "/home/prenotazione.pdf"
    And I fill in "Email referente" with "giuseppe.rubino@gmail.com"
    And I check "Ricezione abstract"
    And I check "Pagina sponsor"
    And I check "Abilitato"
    Given I press "Create"
    Then the response should contain "Congresso creato con successo"

Scenario: Email referente non deve essere obbligatoria
    Given I go to "/"
    And I follow "Login"
    When I fill in "_username" with "giuseppe"
    And I fill in "_password" with "giuseppe"
    Given I press "Login"
    When I am on "/congresso/new"
    When I fill in "Codice congresso" with "TEST89"
    When I fill in "Url" with "http://www.google.com"
    When I fill in "Titolo" with "titolo test"
    When I fill in "Descrizione" with "mia descrizione"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_year" with "2012"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_month" with "09"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_day" with "01"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_year" with "2012"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_month" with "09"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_day" with "01"
    When I fill in "Luogo" with "Roma"
    And I fill in "accreditamenti_congressibundle_congressotype_manifesto" with "/manifeso.jpg"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_programma" with "/home/programma.pdf"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_iscrizione" with "/home/iscrizione.pdf"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_prenotazione" with "/home/prenotazione.pdf"
    When I check "Ricezione abstract"
    When I check "Pagina sponsor"
    When I check "Abilitato"
    Given I press "Create"
    Then the response should contain "Congresso creato con successo"

Scenario: Un Guest non può crere un congresso
    Given I go to "/logout"
    When I am on "/congresso/new"
    Then I should be on "/login"

Scenario: Un Guest non può cancellare un congresso