Feature: Come Admin voglio gestire i congressi

Scenario: As Guest I want to login
    Given I go to "/"
    Then the response should not contain "crea congresso"
    Then the response should not contain "link-crea-nuovo-congresso"
    And I follow "login"
    When I fill in "_username" with "giuseppe"
    And I fill in "_password" with "giuseppe"
    Given I press "Login"
    Then the response should contain "logout (giuseppe)"
    And the response should contain "giuseppe@giuseppe.com"
    Given I go to "/"
    Then the response should contain "Puoi creare un congresso."
    Then the response should contain "link-crea-nuovo-congresso"

Scenario: As User Create a new Congress
    Given I go to "/"
    And I follow "login"
    When I fill in "_username" with "giuseppe"
    And I fill in "_password" with "giuseppe"
    Given I press "Login"
    When I am on "/congresso/new"
    When I fill in "Codice congresso" with "TEST89"
    When I fill in "Url" with "http://www.google.com"
    When I fill in "Titolo" with "titolo test"
    When I fill in "Descrizione" with "mia descrizione"
    # Then show last response
    When I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_year" with "2012"
    When I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_month" with "09"
    When I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_day" with "01"
    When I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_year" with "2012"
    When I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_month" with "09"
    When I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_day" with "01"
    When I fill in "Luogo" with "Roma"
    When I fill in "Manifesto" with "/manifeso.jpg"
    When I fill in "Path pdf programma" with "/home/programma.pdf"
    When I fill in "Path pdf iscrizione" with "/home/iscrizione.pdf"
    When I fill in "Path pdf prenotazione" with "/home/prenotazione.pdf"
    When I fill in "Email referente" with "giuseppe.rubino@gmail.com"
    When I check "Ricezione abstract"
    When I check "Pagina sponsor"
    When I check "Abilitato"
    Given I press "Create"
    Then the response should contain "Congresso creato con successo"

Scenario: Email referente non deve essere obbligatoria
    Given I go to "/"
    And I follow "login"
    When I fill in "_username" with "giuseppe"
    And I fill in "_password" with "giuseppe"
    Given I press "Login"
    When I am on "/congresso/new"
    When I fill in "Codice congresso" with "TEST89"
    When I fill in "Url" with "http://www.google.com"
    When I fill in "Titolo" with "titolo test"
    When I fill in "Descrizione" with "mia descrizione"
    When I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_year" with "2012"
    When I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_month" with "09"
    When I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_day" with "01"
    When I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_year" with "2012"
    When I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_month" with "09"
    When I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_day" with "01"
    When I fill in "Luogo" with "Roma"
    When I fill in "Manifesto" with "/manifeso.jpg"
    When I fill in "Path pdf programma" with "/home/programma.pdf"
    When I fill in "Path pdf iscrizione" with "/home/iscrizione.pdf"
    When I fill in "Path pdf prenotazione" with "/home/prenotazione.pdf"
    When I check "Ricezione abstract"
    When I check "Pagina sponsor"
    When I check "Abilitato"
    Given I press "Create"
    Then the response should contain "Congresso creato con successo"

Scenario: Un Guest non può crere un congresso
    When I am on "/congresso/new"
    Then I should be on "/login"



Scenario: Un Guest non può cancellare un congresso