Feature: Come Admin dentro la pagina show accreditamento voglio creare un questionario ecm

Scenario: As User Create a new Test
    Given I go to "/"
    And I follow "Login"
    When I fill in "_username" with "giuseppe"
    And I fill in "_password" with "giuseppe"
    Given I press "Login"
    When I am on "/congresso/new"
    And I fill in "Codice congresso" with "TEST89"
    And I fill in "Url" with "http://www.google.com"
    And I fill in "Titolo" with "titolo test"
    And I fill in "Descrizione" with "mia descrizione"
    #And I fill in "accreditamenti_congressibundle_congressotype_data_inizio" with "22-12-2012"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_year" with "2012"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_month" with "09"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_day" with "01"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_year" with "2012"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_month" with "09"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_day" with "01"
    And I fill in "Luogo" with "Roma"
    And I fill in "accreditamenti_congressibundle_congressotype_manifesto" with "/manifeso.jpg"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_programma" with "/home/programma.pdf"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_iscrizione" with "/home/iscrizione.pdf"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_prenotazione" with "/home/prenotazione.pdf"
    And I fill in "Email referente" with "giuseppe.rubino@gmail.com"
    And I check "Ricezione abstract"
    And I check "Pagina sponsor"
    And I check "Abilitato"
    Given I press "Create"
    #Then the response should contain "Congresso creato con successo"
    And I follow "Crea accreditamento"
    And I fill in "Numero accreditamento" with "55555"
    And I fill in "Titolo" with "ACCRE-TITOLO"
    And I fill in "Luogo" with "ACCRE-ROMA"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_data_inizio_year" with "2012"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_data_inizio_month" with "12"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_data_inizio_day" with "05"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_data_fine_year" with "2012"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_data_fine_month" with "12"
    And I fill in "accreditamenti_congressibundle_accreditamentotype_data_fine_day" with "08"
    And I fill in "Ore formative" with "44"
    And I fill in "Obiettivo formativo" with "ACCRE-OBIETTIVOOOO"
    And I fill in "Numero crediti" with "11"
    Given I press "Create"
    #Then show last response                                                                                       
    Then the response should contain "Accreditamento creato con successo"
    And I follow "Crea questionario ecm"
    And I fill in "Descrizione" with "Mia Descrizione questionario"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_data_inizio_compilazione_year" with "2012"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_data_inizio_compilazione_month" with "07"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_data_inizio_compilazione_day" with "07"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_data_fine_compilazione_year" with "2012"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_data_fine_compilazione_month" with "07"
    And I fill in "accreditamenti_congressibundle_questionarioecmtype_data_fine_compilazione_day" with "09"
    And I fill in "Percentuale risposte esatte" with "75"
    And I fill in "Numero tentativi compilazione" with "12"
    Given I press "Create"
    Then the response should contain "Questionario creato con successo"
    And I follow "Crea domanda"
    And I fill in "Descrizione" with "quanto erano i porcellini?"
    Given I press "Create"Questionario
    And I follow "Crea risposta"
    And I fill in "Descrizione" with "erano 3"
    And I check "Vero"
    Given I press "Create"

