Feature: Come Admin dentro la pagina show accreditamento voglio gestire i il test

Scenario: As User Create a new Test
    Given I go to "/"
    And I follow "Login"
    When I fill in "_username" with "giuseppe"
    And I fill in "_password" with "giuseppe"
    Given I press "Login"
    When I am on "/congresso/new"
    And I fill in "Codice congresso" with "TEST89"
    And I fill in "Url" with "http://www.google.com"
    And I fill in "Titolo" with "titolo test"
    And I fill in "Descrizione" with "mia descrizione"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_year" with "2012"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_month" with "09"
    And I fill in "accreditamenti_congressibundle_congressotype_data_inizio_date_day" with "01"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_year" with "2012"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_month" with "09"
    And I fill in "accreditamenti_congressibundle_congressotype_data_fine_date_day" with "01"
    And I fill in "Luogo" with "Roma"
    And I fill in "accreditamenti_congressibundle_congressotype_manifesto" with "/manifeso.jpg"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_programma" with "/home/programma.pdf"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_iscrizione" with "/home/iscrizione.pdf"
    And I fill in "accreditamenti_congressibundle_congressotype_path_pdf_prenotazione" with "/home/prenotazione.pdf"
    And I fill in "Email referente" with "giuseppe.rubino@gmail.com"
    And I check "Ricezione abstract"
    And I check "Pagina sponsor"
    And I check "Abilitato"
    Given I press "Create"
    Then the response should contain "Congresso creato con successo"
    Then show last response