<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AccreditamentiCongressiBundleEntityIscrittiProxy extends \Accreditamenti\CongressiBundle\Entity\Iscritti implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setCognome($cognome)
    {
        $this->__load();
        return parent::setCognome($cognome);
    }

    public function getCognome()
    {
        $this->__load();
        return parent::getCognome();
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setCodiceFiscale($codiceFiscale)
    {
        $this->__load();
        return parent::setCodiceFiscale($codiceFiscale);
    }

    public function getCodiceFiscale()
    {
        $this->__load();
        return parent::getCodiceFiscale();
    }

    public function setTipologiaIscritto($tipologiaIscritto)
    {
        $this->__load();
        return parent::setTipologiaIscritto($tipologiaIscritto);
    }

    public function getTipologiaIscritto()
    {
        $this->__load();
        return parent::getTipologiaIscritto();
    }

    public function setAccreditamento(\Accreditamenti\CongressiBundle\Entity\Accreditamento $accreditamento)
    {
        $this->__load();
        return parent::setAccreditamento($accreditamento);
    }

    public function getAccreditamento()
    {
        $this->__load();
        return parent::getAccreditamento();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'cognome', 'nome', 'codice_fiscale', 'tipologia_iscritto', 'accreditamento_id', 'accreditamento');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}