<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AccreditamentiCongressiBundleEntityAnagraficaProxy extends \Accreditamenti\CongressiBundle\Entity\Anagrafica implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setTipoIscrizione($tipoIscrizione)
    {
        $this->__load();
        return parent::setTipoIscrizione($tipoIscrizione);
    }

    public function getTipoIscrizione()
    {
        $this->__load();
        return parent::getTipoIscrizione();
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setCognome($cognome)
    {
        $this->__load();
        return parent::setCognome($cognome);
    }

    public function getCognome()
    {
        $this->__load();
        return parent::getCognome();
    }

    public function setDataNascita($dataNascita)
    {
        $this->__load();
        return parent::setDataNascita($dataNascita);
    }

    public function getDataNascita()
    {
        $this->__load();
        return parent::getDataNascita();
    }

    public function setLuogoNascita($luogoNascita)
    {
        $this->__load();
        return parent::setLuogoNascita($luogoNascita);
    }

    public function getLuogoNascita()
    {
        $this->__load();
        return parent::getLuogoNascita();
    }

    public function setCodiceFiscale($codiceFiscale)
    {
        $this->__load();
        return parent::setCodiceFiscale($codiceFiscale);
    }

    public function getCodiceFiscale()
    {
        $this->__load();
        return parent::getCodiceFiscale();
    }

    public function setOrdineNumero($ordineNumero)
    {
        $this->__load();
        return parent::setOrdineNumero($ordineNumero);
    }

    public function getOrdineNumero()
    {
        $this->__load();
        return parent::getOrdineNumero();
    }

    public function setOrdineCitta($ordineCitta)
    {
        $this->__load();
        return parent::setOrdineCitta($ordineCitta);
    }

    public function getOrdineCitta()
    {
        $this->__load();
        return parent::getOrdineCitta();
    }

    public function setIndirizzo($indirizzo)
    {
        $this->__load();
        return parent::setIndirizzo($indirizzo);
    }

    public function getIndirizzo()
    {
        $this->__load();
        return parent::getIndirizzo();
    }

    public function setIndirizzoCap($indirizzoCap)
    {
        $this->__load();
        return parent::setIndirizzoCap($indirizzoCap);
    }

    public function getIndirizzoCap()
    {
        $this->__load();
        return parent::getIndirizzoCap();
    }

    public function setIndirizzoCitta($indirizzoCitta)
    {
        $this->__load();
        return parent::setIndirizzoCitta($indirizzoCitta);
    }

    public function getIndirizzoCitta()
    {
        $this->__load();
        return parent::getIndirizzoCitta();
    }

    public function setIndirizzoProvincia($indirizzoProvincia)
    {
        $this->__load();
        return parent::setIndirizzoProvincia($indirizzoProvincia);
    }

    public function getIndirizzoProvincia()
    {
        $this->__load();
        return parent::getIndirizzoProvincia();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setCellulare($cellulare)
    {
        $this->__load();
        return parent::setCellulare($cellulare);
    }

    public function getCellulare()
    {
        $this->__load();
        return parent::getCellulare();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setProfessione($professione)
    {
        $this->__load();
        return parent::setProfessione($professione);
    }

    public function getProfessione()
    {
        $this->__load();
        return parent::getProfessione();
    }

    public function setDisciplina($disciplina)
    {
        $this->__load();
        return parent::setDisciplina($disciplina);
    }

    public function getDisciplina()
    {
        $this->__load();
        return parent::getDisciplina();
    }

    public function setQualifica($qualifica)
    {
        $this->__load();
        return parent::setQualifica($qualifica);
    }

    public function getQualifica()
    {
        $this->__load();
        return parent::getQualifica();
    }

    public function setSponsor($sponsor)
    {
        $this->__load();
        return parent::setSponsor($sponsor);
    }

    public function getSponsor()
    {
        $this->__load();
        return parent::getSponsor();
    }

    public function setSponsorAzienda($sponsorAzienda)
    {
        $this->__load();
        return parent::setSponsorAzienda($sponsorAzienda);
    }

    public function getSponsorAzienda()
    {
        $this->__load();
        return parent::getSponsorAzienda();
    }

    public function setPrivacy($privacy)
    {
        $this->__load();
        return parent::setPrivacy($privacy);
    }

    public function getPrivacy()
    {
        $this->__load();
        return parent::getPrivacy();
    }

    public function setAccreditamento(\Accreditamenti\CongressiBundle\Entity\Accreditamento $accreditamento)
    {
        $this->__load();
        return parent::setAccreditamento($accreditamento);
    }

    public function getAccreditamento()
    {
        $this->__load();
        return parent::getAccreditamento();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'tipo_iscrizione', 'nome', 'cognome', 'data_nascita', 'luogo_nascita', 'codice_fiscale', 'ordine_numero', 'ordine_citta', 'indirizzo', 'indirizzo_cap', 'indirizzo_citta', 'indirizzo_provincia', 'telefono', 'cellulare', 'email', 'professione', 'disciplina', 'qualifica', 'sponsor', 'sponsor_azienda', 'privacy', 'accreditamento');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}