<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AccreditamentiCongressiBundleEntityRispostaProxy extends \Accreditamenti\CongressiBundle\Entity\Risposta implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setDescrizione($descrizione)
    {
        $this->__load();
        return parent::setDescrizione($descrizione);
    }

    public function getDescrizione()
    {
        $this->__load();
        return parent::getDescrizione();
    }

    public function setVero($vero)
    {
        $this->__load();
        return parent::setVero($vero);
    }

    public function getVero()
    {
        $this->__load();
        return parent::getVero();
    }

    public function setDomanda(\Accreditamenti\CongressiBundle\Entity\Domanda $domanda)
    {
        $this->__load();
        return parent::setDomanda($domanda);
    }

    public function getDomanda()
    {
        $this->__load();
        return parent::getDomanda();
    }

    public function setAperta($aperta)
    {
        $this->__load();
        return parent::setAperta($aperta);
    }

    public function getAperta()
    {
        $this->__load();
        return parent::getAperta();
    }

    public function setTextarea($textarea)
    {
        $this->__load();
        return parent::setTextarea($textarea);
    }

    public function getTextarea()
    {
        $this->__load();
        return parent::getTextarea();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'descrizione', 'vero', 'aperta', 'textarea', 'domanda');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}